### ISSUE TITLE
Fix storing uid in SecureStorage

### ISSUE THREAD

**Issue by jjchung3** [zotbins/Zotbuddy#5]
storing uid in SecureStorage is failing
the failure happens when we call onSignIn inside LoginForm
I'm guessing its something wrong with importing and exporting from the index.js from src/util

**Comment by jessechong** [comment]
please check this commit - https://github.com/zotbins/Zotbuddy/pull/8/commits/2a795c29ed1558e9938ec0d7bb040144349c5498 
here is the PR - https://github.com/zotbins/Zotbuddy/pull/8

the fix was to import the library again in the file that is actually using it. in this case, importing from `src/utils/` is not enough for SecureStorage. I added another import to `LoginForm.js`

**Comment by jessechong** [comment]
fix was merged. Closing this issue....
